version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    ports:
      - "8032:8032"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://admin:admin@db:5432/BDD  # URL de conexión para PostgreSQL
    depends_on:
      - db

#  db:
#    image: postgres:13
#    container_name: postgres_db
#    environment:
#      POSTGRES_DB: BDD
#      POSTGRES_USER: admin
#      POSTGRES_PASSWORD: admin
#    volumes:
#      - postgres_data:/var/lib/postgresql/data

#volumes:
#  postgres_data:
